[package]
name = "escaper"
version = "1.1.0"
edition = "2021"
desciption = "Escapes special characters for URLS."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

