[package]
name = "escaper"
version = "1.1.0"
edition = "2021"
desciption = "Escapes special character sequences."

[profile.release]
lto = true
debug = true

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "str_bench"
harness = false
